Update and rename aleo3-daniel.sh to aleo3

diff --git a/aleo3 b/aleo3
--- a/aleo3
+++ b/aleo3
@@ -4,12 +4,12 @@ Red_font_prefix="\033[31m"
 Green_background_prefix="\033[42;37m"
 Red_background_prefix="\033[41;37m"
 Font_color_suffix="\033[0m"
-Info="[${Green_font_prefix}信息${Font_color_suffix}]"
-Error="[${Red_font_prefix}错误${Font_color_suffix}]"
+Info="[${Green_font_prefix}訊息${Font_color_suffix}]"
+Error="[${Red_font_prefix}錯誤${Font_color_suffix}]"
 Tip="[${Green_font_prefix}注意${Font_color_suffix}]"
 AleoFile="/root/aleo.txt"
 check_root() {
-    [[ $EUID != 0 ]] && echo -e "${Error} 当前非ROOT账号(或没有ROOT权限)，无法继续操作，请更换ROOT账号或使用 ${Green_background_prefix}sudo su${Font_color_suffix} 命令获取临时ROOT权限（执行后可能会提示输入当前账号的密码）。" && exit 1
+    [[ $EUID != 0 ]] && echo -e "${Error} 目前非ROOT帳號(或沒有ROOT權限)，無法繼續操作，請更換ROOT帳號或使用 ${Green_background_prefix}sudo su${Font_color_suffix} 命令取得臨時ROOT權限（執行後可能會要求輸入當前帳號的密碼）。" && exit 1
 }
 
 install_aleo(){
@@ -37,7 +37,7 @@ source $HOME/.cargo/env
 source /etc/profile
 cd /root/snarkOS
 nohup ./run-client.sh > run-client.log 2>&1 &
-echo "aleo_client启动成功"
+echo "aleo_client啟動成功"
 
 }
 
@@ -46,7 +46,7 @@ source $HOME/.cargo/env
 source /etc/profile
 cd /root/snarkOS
 nohup ./run-prover.sh > run-prover.log 2>&1 &
-echo "aleo_prover启动成功"
+echo "aleo_prover啟動成功"
 }
 
 read_aleo_address(){
@@ -54,16 +54,14 @@ cat /root/aleo.txt
 }
 
 
-echo && echo -e " ${Red_font_prefix}aleo 有奖激励测试3 一键安装脚本${Font_color_suffix} by \033[1;35mDaniel\033[0m
-此脚本完全免费开源，由推特用户 ${Green_font_prefix}Daniel_eth2开发${Font_color_suffix}，
-欢迎关注，如有收费请勿上当受骗。
+echo && echo -e " ${Red_font_prefix}aleo 激勵測試網3 OneKey版本${Font_color_suffix}
  ———————————————————————
- ${Green_font_prefix} 1.安装 aleo ${Font_color_suffix}
- ${Green_font_prefix} 2.运行 aleo_client ${Font_color_suffix}
- ${Green_font_prefix} 3.运行 aleo_prover ${Font_color_suffix}
- ${Green_font_prefix} 4.读取 aleo 地址私钥 ${Font_color_suffix}
+ ${Green_font_prefix} 1.安裝 aleo ${Font_color_suffix}
+ ${Green_font_prefix} 2.執行 aleo_client ${Font_color_suffix}
+ ${Green_font_prefix} 3.執行 aleo_prover ${Font_color_suffix}
+ ${Green_font_prefix} 4.讀取 aleo 地址私鑰 ${Font_color_suffix}
  ———————————————————————" && echo
-read -e -p " 请输入数字 [1-4]:" num
+read -e -p " 請輸入數字 [1-4]:" num
 case "$num" in
 1)
     install_aleo
@@ -79,6 +77,6 @@ case "$num" in
     ;;
 *)
     echo
-    echo -e " ${Error} 请输入正确的数字"
+    echo -e " ${Error} 請輸入正確的數字"
     ;;
 esac
